### ISSUE TITLE
Issues reproducing cityscapes -> foggycityscapes

### ISSUE THREAD

**Issue by just-eoghan** [yuhuayc/sa-da-faster#4]
Hello, I am having trouble reproducing the results on the cityscapes -> foggy-cityscapes results from the paper. https://link.springer.com/article/10.1007/s11263-021-01447-x

The results in the paper are as follows:
![image](https://user-images.githubusercontent.com/82596496/199742808-b35b1e32-207b-47a9-beb5-fe59f3ead7d3.png)

The config file I used is as follows: (I based this config from information from the paper so it might be wrong .. It would be great if you could push the config file used to produce these results #3)

```
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  DOMAIN_ADAPTATION_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    NUM_CLASSES: 9
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  DA_HEADS:
    DA_IMG_GRL_WEIGHT: 0.01
    DA_INS_GRL_WEIGHT: 0.1
    COS_WEIGHT: 0.1
DATASETS:
  TRAIN: ("cityscapes_fine_instanceonly_seg_train_cocostyle",)
  SOURCE_TRAIN: ("cityscapes_fine_instanceonly_seg_train_cocostyle",)
  TARGET_TRAIN: ("foggy_cityscapes_fine_instanceonly_seg_train_cocostyle",)
  TEST: ("foggy_cityscapes_fine_instanceonly_seg_val_cocostyle",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1600
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1600
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (30000, 40000)
  MAX_ITER: 60000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 1
```
The results from this run are as follows.

```
2022-11-03 14:11:34,888 maskrcnn_benchmark.inference INFO: Start evaluation on foggy_cityscapes_fine_instanceonly_seg_val_cocostyle dataset(500 images).
100%|######################################################################################| 500/500 [00:57<00:00,  8.65it/s]
2022-11-03 14:12:32,681 maskrcnn_benchmark.inference INFO: Total inference time: 0:00:57.792687 (0.11558537435531616 s / img per device, on 1 devices)
2022-11-03 14:12:32,749 maskrcnn_benchmark.inference INFO: Preparing results for COCO format
2022-11-03 14:12:32,749 maskrcnn_benchmark.inference INFO: Preparing bbox results
2022-11-03 14:12:32,933 maskrcnn_benchmark.inference INFO: Evaluating predictions
Loading and preparing results...
DONE (t=0.19s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=1.34s).
Accumulating evaluation results...
DONE (t=0.41s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.022
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.035
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.026
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.007
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.051
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.029
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.044
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.057
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.093
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.055
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.089
2022-11-03 14:12:35,250 maskrcnn_benchmark.inference INFO: OrderedDict([('bbox', OrderedDict([('AP', 0.021931884420795272), ('AP50', 0.03519164698390678), ('AP75', 0.02558192590466571), ('APs', 0.0005268655029334559), ('APm', 0.007046457698924455), ('APl', 0.0506087860529293)]))])
```

The result I get for mAP 50 is 0.03519164698390678 which is far below the reported 44.0. Obviously I am doing something incorrectly to get this low result.

I have verified that my cityscapes data is correct. It is in coco format xywh which is converted to xyxy by your code https://github.com/yuhuayc/sa-da-faster/blob/dda678f0befd849329ee8539f62c738410587b80/maskrcnn_benchmark/data/datasets/coco.py#L76

It may be a versioning / package issue? If you have a log file from your cityscapes run adding it to the repo would be a fantastic addition. 

My versions are as follows:
```
2022-11-03 00:22:47,713 maskrcnn_benchmark INFO: Using 1 GPUs
2022-11-03 00:22:47,713 maskrcnn_benchmark INFO: Namespace(config_file='configs/da_faster_rcnn/e2e_da_faster_rcnn_R_50_FPN_cityscapes.yaml', distributed=False, local_rank=0, opts=[], skip_test=False)
2022-11-03 00:22:47,714 maskrcnn_benchmark INFO: Collecting env info (might take some time)
2022-11-03 00:22:49,349 maskrcnn_benchmark INFO: 
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.7 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 SUPER
GPU 1: NVIDIA GeForce RTX 2080 SUPER

Nvidia driver version: 470.141.03
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.1.0
[pip3] torchvision==0.2.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py36he8ac12f_0  
[conda] mkl_fft                   1.3.0            py36h54f3939_0  
[conda] mkl_random                1.1.1            py36h0573a6f_0  
[conda] pytorch                   1.1.0           py3.6_cuda10.0.130_cudnn7.5.1_0    pytorch
[conda] torchvision               0.2.1                    pypi_0    pypi
        Pillow (8.3.1)
```

This is my training log file 
[log.txt](https://github.com/yuhuayc/sa-da-faster/files/9930022/log.txt)

I hope you can help me on this!

Thank you for your work.
